name: Deploy

on:
  push:
    branches:
      - jbake

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JBAKE_VERSION: "2.6.7"
      JBAKE_SHA1: "fd07b833104f2889fde9a07d0c0bf09f0fdecbf6"
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            downloads/*.zip
          key: ${{ runner.os }}-${{ env.JBAKE_VERSION }}
      - run: |
          mkdir -p downloads
          cd downloads
          if [[ ! -f "jbake-${JBAKE_VERSION}-bin.zip" ]]; then
            wget "https://github.com/jbake-org/jbake/releases/download/v${JBAKE_VERSION}/jbake-${JBAKE_VERSION}-bin.zip"
          fi
          sha1sum "jbake-${JBAKE_VERSION}-bin.zip"
          echo "${JBAKE_SHA1}  jbake-${JBAKE_VERSION}-bin.zip.sha" > "jbake-${JBAKE_VERSION}-bin.zip.sha"
          sha1sum -c "jbake-${JBAKE_VERSION}-bin.zip.sha"
          unzip "jbake-${JBAKE_VERSION}-bin.zip.sha"
          ls
          mv jbake ../bin
      - run: ./bin/jbake
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: ./script/deploy.sh
        env:
          AWS_BUCKET: typedclojure.org
